name: Dependency Review

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  dependency_review:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm ci

    - name: Dependabot Review
      uses: dependabot/dependabot-core@0.150.x
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        directory: '.'

